apiVersion: v1
kind: Service
metadata:
  name: api-backend-service
  labels:
    app: api-backend
spec:
  type: ClusterIP
  selector:
    app: api-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
